//
// Created by Tim Holzhey on 19.06.23.
//

#ifndef HTTP_SERVER_HTTP_SERVER_PROTOCOL_H
#define HTTP_SERVER_HTTP_SERVER_PROTOCOL_H

typedef enum {
	HTTP_SERVER_PROTOCOL_HTTP,
	HTTP_SERVER_PROTOCOL_WEBSOCKET,
} http_server_protocol_t;

#endif //HTTP_SERVER_HTTP_SERVER_PROTOCOL_H
